version: alpha

accounts:
  - name: account-1
    id: 1
  - name: account-2
    id: 2

pipelines:
  patch-top-level:
  - task: call
    destination: $account-1
    params:
      value: '{"string":"hello"}'
      entrypoint: default
      patch:
        - path: ''
          type: address
          value: $account-1
          optimized: false

  patch-timestamp:
  - task: call
    destination: $account-1
    params:
      value: '{"string":"2023-10-10T06:58:16Z"}'
      entrypoint: default
      patch:
        - path: ''
          type: timestamp
          value: $now+24h
          optimized: false
